kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-api-gateway-upstream-conf
data:
  api-gateway.conf: |-
    upstream api_upstream {
        server {{ .Release.Name }}-devicehive-frontend:8080;
    }
    upstream auth_upstream {
        server {{ .Release.Name }}-devicehive-auth:8090;
    }
    upstream plugin_upstream {
        server {{ .Release.Name }}-devicehive-plugin:8110;
    }
