---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-hazelcast"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.hazelcast.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-hazelcast
    spec:
      containers:
      - name: devicehive-hazelcast
        image: {{ .Values.devicehive.repository }}/devicehive-hazelcast:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: MIN_HEAP_SIZE
          value: "512m"
        - name: MAX_HEAP_SIZE
          value: "512m"
        ports:
        - name: hazelcast
          containerPort: 5701
        resources:
{{ toYaml .Values.devicehive.hazelcast.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-auth
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-auth"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.auth.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-auth
    spec:
      containers:
      - name: devicehive-auth
        image: {{ .Values.devicehive.repository}}/devicehive-auth:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: "{{ .Values.devicehive.db.name }}-postgresql"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwtsecret
              key: jwtsecret
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: dh-auth
          containerPort: 8090
        resources:
{{ toYaml .Values.devicehive.auth.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-frontend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-frontend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-frontend
    spec:
      containers:
      - name: devicehive-frontend
        image: {{ .Values.devicehive.repository }}/devicehive-frontend:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_AUTH_URL
          value: "http://{{ .Release.Name }}-devicehive-auth:8090/auth/rest"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: "{{ .Values.devicehive.db.name }}-postgresql"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwtsecret
              key: jwtsecret
        ports:
        - name: dh-api
          containerPort: 8080
        resources:
{{ toYaml .Values.devicehive.frontend.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-backend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-backend
    spec:
      containers:
      - name: devicehive-backend
        image: {{ .Values.devicehive.repository }}/devicehive-backend:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: "{{ .Values.devicehive.db.name }}-postgresql"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        resources:
{{ toYaml .Values.devicehive.backend.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-plugin
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-plugin"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.plugin.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-plugin
    spec:
      containers:
      - name: devicehive-plugin
        image: {{ .Values.devicehive.repository }}/devicehive-plugin:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_AUTH_URL
          value: "http://{{ .Release.Name }}-devicehive-auth:8090/api/rest"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: "{{ .Values.devicehive.db.name }}-postgresql"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: DH_RPC_CLIENT_RES_CONS_THREADS
          value: "3"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: dh-plugin
          containerPort: 8110
        resources:
{{ toYaml .Values.devicehive.plugin.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-proxy
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-devicehive-proxy"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehiveProxy.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-proxy
    spec:
      containers:
      - name: devicehive-proxy
        image: {{ .Values.devicehiveProxy.repository }}/devicehive-proxy:{{ .Values.devicehiveProxy.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            path: /admin/
            port: http
          initialDelaySeconds: 60
          periodSeconds: 3
        volumeMounts:
        - name: api-gateway-upstream-conf
          mountPath: /etc/nginx/upstream.d
      volumes:
        - name: api-gateway-upstream-conf
          configMap:
            name: {{ .Release.Name }}-api-gateway-upstream-conf
            items:
            - key: api-gateway.conf
              path: api-gateway.conf
...
