---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-hazelcast"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.hazelcast.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-hazelcast
    spec:
      containers:
      - name: devicehive-hazelcast
        image: {{ .Values.devicehive.repository }}/devicehive-hazelcast:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: MIN_HEAP_SIZE
          value: "512m"
        - name: MAX_HEAP_SIZE
          value: "512m"
        ports:
        - name: hazelcast
          containerPort: 5701
        resources:
{{ toYaml .Values.devicehive.hazelcast.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-auth
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-auth"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.auth.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-auth
    spec:
      containers:
      - name: devicehive-auth
        image: {{ .Values.devicehive.repository}}/devicehive-auth:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: {{ template "postgresql.fullname" . }}
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwtsecret
              key: jwtsecret
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: dh-auth
          containerPort: 8090
        resources:
{{ toYaml .Values.devicehive.auth.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-frontend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-frontend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-frontend
    spec:
      containers:
      - name: devicehive-frontend
        image: {{ .Values.devicehive.repository }}/devicehive-frontend:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_AUTH_URL
          value: "http://{{ .Release.Name }}-devicehive-auth:8090/auth/rest"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: {{ template "postgresql.fullname" . }}
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        {{- if .Values.wsproxy.internal.enabled }}
        - name: DH_WS_PROXY
          value: "{{ .Release.Name }}-devicehive-ws-proxy-internal:3000"
        - name: SPRING_PROFILES_ACTIVE
          value: "ws-kafka-proxy-frontend"
        {{- end }}
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwtsecret
              key: jwtsecret
        ports:
        - name: dh-api
          containerPort: 8080
        resources:
{{ toYaml .Values.devicehive.frontend.resources | indent 10 }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-backend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-backend
    spec:
      containers:
      - name: devicehive-backend
        image: {{ .Values.devicehive.repository }}/devicehive-backend:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.devicehive.kafka.name }}-kafka:9092"
        - name: DH_POSTGRES_ADDRESS
          value: {{ template "postgresql.fullname" . }}
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: DH_ZK_ADDRESS
          value: "{{ .Values.devicehive.kafka.name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        {{- if .Values.wsproxy.internal.enabled }}
        - name: DH_WS_PROXY
          value: "{{ .Release.Name }}-devicehive-ws-proxy-internal:3000"
        - name: SPRING_PROFILES_ACTIVE
          value: "ws-kafka-proxy-backend"
        {{- end }}
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        resources:
{{ toYaml .Values.devicehive.backend.resources | indent 10 }}
...
