apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-backend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-backend
    spec:
      containers:
      - name: devicehive-backend
        image: {{ .Values.devicehive.repository }}/devicehive-backend:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: {{ template "kafka.fullname" . }}:9092
        - name: DH_POSTGRES_ADDRESS
          value: {{ template "postgresql.fullname" . }}
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: DH_ZK_ADDRESS
          value: {{ template "zookeeper.fullname" . }}
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_WS_PROXY
          value: "{{ .Release.Name }}-devicehive-ws-proxy-internal:3000"
        {{- if eq .Values.devicehive.bus "rpc" }}
        - name: SPRING_PROFILES_ACTIVE
          value: "rpc-server"
        {{- end }}
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        resources:
{{ toYaml .Values.devicehive.backend.resources | indent 10 }}
