apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-hazelcast"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.javaServer.hazelcast.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-hazelcast
    spec:
      containers:
      - name: devicehive-hazelcast
        image: "{{ .Values.javaServer.repository }}/devicehive-hazelcast:{{ .Values.javaServer.tag }}"
        imagePullPolicy: {{ .Values.javaServer.PullPolicy }}
        env:
        - name: MIN_HEAP_SIZE
          value: "512m"
        - name: MAX_HEAP_SIZE
          value: "512m"
        ports:
        - name: hazelcast
          containerPort: 5701
        resources:
{{ toYaml .Values.javaServer.hazelcast.resources | indent 10 }}
