{{- if .Values.devicehive.plugin.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-plugin
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-plugin"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.devicehive.plugin.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-plugin
    spec:
      containers:
      - name: devicehive-plugin
        image: {{ .Values.devicehive.repository }}/devicehive-plugin:{{ .Values.devicehive.tag }}
        imagePullPolicy: {{ .Values.devicehive.PullPolicy }}
        env:
        - name: DH_AUTH_URL
          value: "http://{{ .Release.Name }}-devicehive-auth:8090/auth/rest"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: {{ template "kafka.fullname" . }}:9092
        - name: DH_POSTGRES_ADDRESS
          value: {{ template "postgresql.fullname" . }}
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: DH_RPC_CLIENT_RES_CONS_THREADS
          value: "3"
        - name: DH_WS_PROXY
          value: "{{ .Release.Name }}-devicehive-ws-proxy-internal:3000"
{{- if .Values.wsProxy.external.enabled }}
        - name: DH_PROXY_PLUGIN_CONNECT
          value: "ws://localhost/plugin/proxy"
{{- end }}
        - name: DH_ZK_ADDRESS
          value: {{ template "zookeeper.fullname" . }}
        - name: DH_ZK_PORT
          value: "2181"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwtsecret
              key: jwtSecret
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: dh-plugin
          containerPort: 8110
        resources:
{{ toYaml .Values.devicehive.plugin.resources | indent 10 }}
{{- end -}}
