---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-auth
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-auth
  ports:
    - protocol: TCP
      port: 8090
      targetPort: dh-auth
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-hazelcast
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-hazelcast
  ports:
    - protocol: TCP
      port: 5701
      targetPort: hazelcast
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-frontend
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: dh-api
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-plugin
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-plugin
  ports:
    - protocol: TCP
      port: 8110
      targetPort: dh-plugin
...
