{{- if .Values.wsProxy.external.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-ws-proxy-external
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-ws-proxy"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.wsProxy.internal.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-ws-proxy-external
    spec:
      containers:
      - name: devicehive-ws-proxy-external
        image: {{ .Values.wsProxy.repository }}/devicehive-ws-proxy:{{ .Values.wsProxy.tag }}
        imagePullPolicy: {{ .Values.wsProxy.PullPolicy }}
        env:
        - name: ENVSEPARATOR
          value: '_'
        - name: KAFKA_KAFKA_HOSTS
          value: {{ template "kafka.fullname" . }}:9092
        - name: PLUGIN_MANAGER_AUTH_SERVICE_ENDPOINT
          value: http://dh_auth:8090/auth/rest
        - name: PLUGIN_MANAGER_PLUGIN_MANAGEMENT_SERVICE_ENDPOINT
          value: http://dh_plugin:8110/plugin/rest
        - name: PROXY_ENABLE_PLUGIN_MANAGER
          value: 'true'
        - name: PROXY_WEB_SOCKET_SERVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: ws-proxy
          containerPort: 3000
        resources:
{{ toYaml .Values.wsProxy.resources | indent 10 }}
{{- end }}
