devicehive:
  repository: devicehive
  tag: 3.4.4
  pullPolicy: IfNotPresent
  auth:
    replicaCount: 1
    resources: {}
  backend:
    replicaCount: 1
    resources: {}
  frontend:
    replicaCount: 1
    resources: {}
  hazelcast:
    replicaCount: 1
    resources: {}
  plugin:
    enabled: false
    replicaCount: 1
    resources: {}
  # Connection method to Kafka
  # wsproxy: connect to Kafka via devicehive-ws-proxy, default
  # rpc: direct connection to Kafka
  bus: wsproxy

  ## JWT secret is used to sign and verify tokens
  ## If not set, a random 16 characters secret will be used
  jwtSecret: ""

  kafka:
    name: devicehive-bus

wsProxy:
  repository: devicehive
  tag: 1.1.0
  pullPolicy: IfNotPresent
  internal:
    replicaCount: 1
    resources: {}
  external:
    enabled: false
    replicaCount: 1
    resources: {}

devicehiveProxy:
  repository: devicehive
  tag: 3.4.4
  pullPolicy: IfNotPresent
  ingress:
    enabled: false
    annotations: {}
    #  kubernetes.io/ingress.class: nginx
    hosts: []

# External dependencies
# PostgreSQL
postgresql:
  enabled: true
  postgresDatabase: devicehivedb
  postgresUser: devicehive
  postgresPassword: devicehivepassword
  persistence:
    enabled: true
    size: 1Gi
  imageTag: 10

# Apache Kafka
kafka:
  enabled: true
