javaServer:
  repository: devicehive
  tag: 3.4.5
  pullPolicy: IfNotPresent
  auth:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  backend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: INFO
  frontend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  hazelcast:
    replicaCount: 1
    resources: {}
  plugin:
    enabled: false
    pluginConnectUrl: ""
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  # Connection method to Kafka
  # wsproxy: connect to Kafka via devicehive-ws-proxy, default
  # rpc: direct connection to Kafka
  bus: wsproxy

  ## JWT secret is used to sign and verify tokens
  ## If not set, a random 16 characters secret will be used
  jwtSecret: ""

wsProxy:
  image: devicehive/devicehive-ws-proxy:1.1.0
  pullPolicy: IfNotPresent
  internal:
    replicaCount: 1
    resources: {}
  external:
    enabled: false
    replicaCount: 1
    resources: {}

proxy:
  image: devicehive/devicehive-proxy:3.4.5
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  ingress:
    enabled: false
    annotations: {}
    #  kubernetes.io/ingress.class: nginx
    hosts: []

rbac:
  create: true
  serviceAccountName: default

# External dependencies
# PostgreSQL
postgresql:
  enabled: true
  postgresDatabase: devicehivedb
  postgresUser: devicehive
  postgresPassword: devicehivepassword
  persistence:
    enabled: true
    size: 1Gi
  imageTag: 10

# Apache Kafka
kafka:
  enabled: true
