version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "7071:7071"
      - "9092:9092"
    links:
      - "zookeeper"
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OPTS: "${KAFKA_OPTS} -javaagent:/opt/kafka/jmx_prometheus_javaagent-0.10.jar=7071:/opt/kafka/kafka-0-8-2.yml"
    volumes:
      - ../lib/jmx_prometheus_javaagent-0.10.jar:/opt/kafka/jmx_prometheus_javaagent-0.10.jar:ro,z
      - ../lib/kafka-0-8-2.yml:/opt/kafka/kafka-0-8-2.yml:ro,z
 
  coordinator:
    image: devicehive/devicehive-riakts
    ports:
      - "8087:8087"
      - "8098:8098"
    restart: unless-stopped
    environment:
      - CLUSTER_NAME=riakts
    labels:
      - "com.basho.riak.cluster.name=riakts"
  member:
    image: devicehive/devicehive-riakts
    ports:
      - "8087"
      - "8098"
    command: bash -c "sleep 30; /usr/lib/riak/riak-cluster.sh" # wait until coordinator starts and activates datatype
    labels:  
      - "com.basho.riak.cluster.name=riakts"
    links:
      - "coordinator"
    depends_on:
      - "coordinator"
    restart: unless-stopped
    environment:
      - CLUSTER_NAME=riakts
      - COORDINATOR_NODE=coordinator
  
  dh_admin:
    image: devicehive/admin-console:${DH_ADMIN_TAG:-development}
    ports:
      - "${DH_ADMIN_PORT:-80}:8080"
    links:
      - "dh_frontend"
    restart: unless-stopped
    environment:
      DH_HOST: dh_frontend
      DH_PORT: 8080

  dh_frontend:
    image: devicehive/devicehive-frontend-riak:${DH_TAG:-development}
    ports:
      - "${DH_FRONTEND_PORT:-8080}:8080"
    links:
      - "zookeeper"
      - "kafka"
      - "coordinator"
      - "member"
    restart: unless-stopped
    environment:
      DH_ZK_ADDRESS: zookeeper
      DH_ZK_PORT: 2181
      DH_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DH_RIAK_HOST: coordinator
      DH_RIAK_PORT: 8087
      DH_RIAK_HTTP_PORT: 8098
      JWT_SECRET: ${JWT_SECRET}

  hazelcast:
    image: devicehive/devicehive-hazelcast:${DH_TAG:-development}
    ports:
      - "5701:5701"
    restart: unless-stopped
    environment:
      MAX_HEAP_SIZE: "512m"

  dh_backend:
    image: devicehive/devicehive-backend-riak:${DH_TAG:-development}
    links:
      - "coordinator"
      - "hazelcast"
      - "kafka"
      - "member"
      - "zookeeper"
    restart: unless-stopped
    environment:
      DH_ZK_ADDRESS: zookeeper
      DH_ZK_PORT: 2181
      DH_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DH_RIAK_HOST: coordinator
      DH_RIAK_PORT: 8087
      DH_RIAK_HTTP_PORT: 8098
      DH_RIAK_HOST_MEMBER: member
      HC_MEMBERS: hazelcast
      HC_GROUP_NAME: ${HC_GROUP_NAME:-dev}
      HC_GROUP_PASSWORD: ${HC_GROUP_PASSWORD:-dev-pass}

volumes:
  schemas:
    external: false
